# Default values for Sentinel (clusters)

sentinel:
  image:
    # make install will substitute this by data coming from terraform
    registry: CHANGE_THIS
    #TODO: this should be removed when we publish the image to hyperfleet-sentinel repository instead of sentinel
    repository: sentinel

  config:
    resourceType: clusters
    resourceSelector: []
    hyperfleetApi:
      baseUrl: http://hyperfleet-api:8000

  broker:
    type: googlepubsub
    # make install will substitute this by data coming from terraform
    topic: CHANGE_THIS
    googlepubsub:
      # make install will substitute this by data coming from terraform
      projectId: CHANGE_THIS
    rabbitmq:
      # make install will substitute this by data coming from tf-helm-values.sh
      url: CHANGE_THIS
      exchangeType: topic
